name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        working-directory: ./js
      - run: npm test
        working-directory: ./js

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./js
      - run: cp names.json js
      - run: npm publish
        working-directory: ./js
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
